const SUBJECTS={
 eni:{id:'eni',icon:'💡',title:'Entrepreneurship & Innovation',code:'EAI 1200',subtitle:'Build, test, and launch your ideas.',color:'green',strengths:['BML','Moats'],focus:['Unit Economics','PMF'],blocks:[
  {id:'hypothesis',title:'Hypothesis',detail:'Find problems worth solving and turn assumptions into testable hypotheses.',topics:['Problem hunting','Riskiest assumption','Hypothesis','Customer discovery']},
  {id:'experiment',title:'Experiment',detail:'Design tests that produce evidence, not opinions.',topics:['Build–Measure–Learn','MVP','Validated learning','Actionable metrics']},
  {id:'prototype',title:'Prototype',detail:'Create artifacts that let users react and behave.',topics:['Prototype','First artifact','User testing','Feedback']},
  {id:'business',title:'Business',detail:'Check if the idea can survive economically and competitively.',topics:['PMF','Pivot vs persevere','Moats','Distribution','Unit economics']},
  {id:'pitch',title:'Pitch',detail:'Explain the problem, solution, traction, business model, and next step.',topics:['Financial model','Pitch','Demo Day','100 users']}
 ],glossary:[['Entrepreneurship','Discovering and acting on opportunities to create value.'],['Riskiest assumption','The belief that kills the idea if it is false.'],['MVP','The smallest artifact that creates learning evidence.'],['PMF','When users would be very disappointed if the product disappeared.'],['CAC','Cost to acquire one paying customer.'],['LTV','Profit from one customer over their lifetime.'],['Moat','A durable advantage that becomes hard to copy.']]},
 spanish:{id:'spanish',icon:'ñ',title:'Spanish A1 / ELE',code:'Curso de Español como Lengua Extranjera',subtitle:'Learn Spanish for everyday life in Chile.',color:'purple',strengths:['Greetings','Basic phrases'],focus:['Vocabulary','Present tense'],blocks:[
  {id:'resources',title:'Classroom survival phrases',detail:'Ask for help, repeat, and clarify in Spanish.',topics:['¿Cómo se dice...?','¿Qué significa...?','No entiendo','Otra vez, por favor']},
  {id:'introductions',title:'Introductions in Chile',detail:'Introduce yourself formally and informally.',topics:['Yo soy','Me llamo','Mucho gusto','¿Cómo te llamas?']},
  {id:'greetings',title:'Greetings and goodbyes',detail:'Use formal and informal greetings naturally.',topics:['Buenos días','Hola, ¿qué tal?','Hasta luego','Nos vemos']},
  {id:'food',title:'Food, shopping, and restaurants',detail:'Order, ask prices, express tastes and needs.',topics:['Me gusta','Quiero','Cuánto cuesta','Eso es todo']},
  {id:'city',title:'City, transport, and daily life',detail:'Talk about location, existence, routines, and movement.',topics:['Hay','Está','Voy a','Lugares en la ciudad']},
  {id:'tourism',title:'Tourism and opinions',detail:'Talk about plans, places, and opinions in Chile.',topics:['Me gustaría','Pienso que','Porque','Lugares turísticos']}
 ],glossary:[['¿Cómo se dice ___?','How do you say ___?'],['¿Qué significa ___?','What does ___ mean?'],['No entiendo','I do not understand.'],['Otra vez, por favor','Again, please.'],['Me llamo','My name is.'],['Mucho gusto','Nice to meet you.'],['Nos vemos','See you.']]}
};
const QUESTIONS={eni:[
 {topic:'Hypothesis',q:'Which hypothesis is strongest?',choices:['Students need help.','Our app will be popular.','At least 6/10 students who scan the QR finish one module.','People like education.'],a:2,trap:'The wrong answers are vague. A strong hypothesis has behavior + number + target group.',retry:'Create one hypothesis with a number and a time limit.'},
 {topic:'PMF',q:'A team asks 8 close friends if they like the app. 6 say yes. What is the trap?',choices:['This proves PMF.','The sample is biased and liking is weak evidence.','Friends are always reliable users.','PMF only applies to paid apps.'],a:1,trap:'PMF is not polite liking. It needs active users and stronger evidence.',retry:'What PMF question would you ask active users?'},
 {topic:'Unit Economics',q:'CAC should be calculated using:',choices:['All website visitors','All signups','Paying customers acquired','Instagram followers'],a:2,trap:'CAC is about acquiring paying customers, not attention or signups.',retry:'If marketing cost is $100 and 5 paying customers are acquired, what is CAC?'},
 {topic:'Moats',q:'Which is NOT a strong moat?',choices:['Network effects','Switching costs','We had the idea first','Regulatory barriers'],a:2,trap:'Being first is easy to copy. A moat must stay defensible over time.',retry:'Name one moat Nash could develop.'}],
spanish:[
 {topic:'Introductions',q:'How do you say “My name is Hesham” informally?',choices:['Yo llamo Hesham','Me llamo Hesham','Soy llamo Hesham','Mi llamo Hesham'],a:1,trap:'Use the reflexive verb llamarse: me llamo = my name is.',retry:'Say: “My name is Sara” in Spanish.'},
 {topic:'Classroom phrases',q:'What does “No entiendo” mean?',choices:['I understand','I do not understand','I am sorry','Again please'],a:1,trap:'No entiendo is the key survival phrase when you are lost.',retry:'How do you ask the teacher to repeat?'},
 {topic:'Greetings',q:'Which greeting is more formal?',choices:['Hola','Buenos días','¿Qué tal?','Nos vemos'],a:1,trap:'Buenos días / buenas tardes / buenas noches are safer formal greetings.',retry:'Give one informal greeting.'},
 {topic:'Introductions',q:'Choose the correct form: Tú ___ llamas Ana.',choices:['me','te','se','nos'],a:1,trap:'Tú uses te: tú te llamas.',retry:'Complete: Yo ___ llamo Omar.'}]};
const FLASHCARDS={eni:[['BML','Build–Measure–Learn. Memory trick: Learn first, build last.'],['MVP','Smallest artifact that creates learning evidence.'],['CAC','Only paying customers count.'],['Pivot','Same vision, new route.'],['PMF','Would users miss you if you disappeared?']],spanish:[['¿Cómo se dice ___?','How do you say ___?'],['No entiendo','I do not understand.'],['Me llamo...','My name is...'],['Mucho gusto','Nice to meet you.'],['Nos vemos','See you.']]};
const initialState={route:'home',subject:'eni',completed:{eni:{},spanish:{}},scores:{eni:{correct:0,total:0},spanish:{correct:0,total:0}},practiceCount:{eni:0,spanish:0},confidence:{eni:2,spanish:1},chat:[],lastMistake:null,feedback:[],memory:{eni:{known:[],weak:[],history:[]},spanish:{known:[],weak:[],history:[]}},uploads:[],coachPlan:null,generatedFlashcards:{eni:[],spanish:[]},mock:{eni:[],spanish:[]},conversation:[]};
let state=JSON.parse(localStorage.getItem('nash52')||'null')||structuredClone(initialState);const app=document.getElementById('app');
function save(){localStorage.setItem('nash52',JSON.stringify(state));}function S(){return SUBJECTS[state.subject];}function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function readiness(id=state.subject){const sc=state.scores[id]||{correct:0,total:0}, comp=Object.keys(state.completed[id]||{}).length, total=SUBJECTS[id].blocks.length;return Math.min(100,Math.round((sc.total?sc.correct/sc.total*42:0)+(comp/total*25)+Math.min(20,(state.practiceCount[id]||0)*4)+((state.memory[id]?.known?.length||0)*2)));}
function setRoute(r){state.route=r;save();render();}window.setRoute=setRoute;function navActive(){document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));}
document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset Nash local progress?')){localStorage.removeItem('nash52');location.reload();}};
function contextPayload(){return {activeSubject:S().title,subjectId:state.subject,readinessScore:readiness(),strongest:S().strengths,weakest:S().focus,completedModules:Object.keys(state.completed[state.subject]||{}),score:state.scores[state.subject],practiceCount:state.practiceCount[state.subject]||0,lastMistake:state.lastMistake,known:state.memory[state.subject].known,weak:state.memory[state.subject].weak,uploadedNotes:state.uploads.slice(-2).map(u=>({name:u.name,preview:u.text?.slice(0,700)}))};}
async function askAI(message,extra={}){const res=await fetch('/.netlify/functions/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,context:{...contextPayload(),...extra}})});const data=await res.json();return data.reply||data.error||'No reply received.';}
function subjectCards(){return Object.values(SUBJECTS).map(s=>`<button class="subject-card ${state.subject===s.id?'active':''}" onclick="selectSubject('${s.id}')"><div class="icon ${s.color==='purple'?'purple':''}">${s.icon}</div><div><h3>${s.title}</h3><p class="muted">${s.subtitle}</p></div></button>`).join('');}window.selectSubject=id=>{state.subject=id;save();render();};
function home(){app.innerHTML=`<section class="card hero"><span class="badge">V5.2 Multi-subject AI</span><h2>Choose your subject and let Nash guide you.</h2><p class="lead">Now with AI flashcards, learning memory, mock exams, Spanish conversation mode, study coach, voice input, professor translator, and upload/paste notes.</p><div class="grid">${subjectCards()}</div></section><section class="grid3"><button class="action-card" onclick="setRoute('coach')"><div class="icon">◈</div><div><h3>Today's Study Coach</h3><p class="muted">Generate a personal plan.</p></div></button><button class="action-card" onclick="setRoute('mockexam')"><div class="icon">✍</div><div><h3>Mock Exam</h3><p class="muted">Practice like the real test.</p></div></button><button class="action-card" onclick="setRoute('conversation')"><div class="icon purple">☷</div><div><h3>Spanish Conversation</h3><p class="muted">Roleplay and correction.</p></div></button></section>`;}
function dashboard(){const r=readiness(), sc=state.scores[state.subject], comp=Object.keys(state.completed[state.subject]||{}).length;app.innerHTML=`<section class="card"><span class="badge">Dashboard</span><h2>${S().title}</h2><div class="kpis"><div class="kpi"><span>Readiness</span><strong>${r}%</strong><div class="progress ${S().color==='purple'?'purple':''}"><span style="width:${r}%"></span></div></div><div class="kpi"><span>Modules</span><strong>${comp}/${S().blocks.length}</strong></div><div class="kpi"><span>Practice</span><strong>${state.practiceCount[state.subject]||0}</strong></div><div class="kpi"><span>Quiz score</span><strong>${sc.total?Math.round(sc.correct/sc.total*100):0}%</strong></div></div></section><section class="card"><h2>Recommended next step</h2><p class="lead">${r<40?'Start with Paths, then do 5 practice questions.':r<70?'Do a mock exam and ask Nash to explain mistakes.':'Use mock exams and flashcards for polishing.'}</p><button class="primary" onclick="setRoute('coach')">Generate detailed plan</button></section>`;}
function paths(){app.innerHTML=`<section class="card"><span class="badge">Paths</span><h2>${S().title} modules</h2><div class="grid">${S().blocks.map(b=>`<div class="module-card"><div class="icon ${S().color==='purple'?'purple':''}">${state.completed[state.subject][b.id]?'✓':'→'}</div><div><h3>${b.title}</h3><p class="muted">${b.detail}</p><p>${b.topics.map(t=>`<button class="pill" onclick="askTopic('${t.replaceAll("'","\\'")}')">${t}</button>`).join(' ')}</p><button class="primary small" onclick="completeModule('${b.id}')">Mark complete</button></div></div>`).join('')}</div></section>`;}window.completeModule=id=>{state.completed[state.subject][id]=true;state.memory[state.subject].history.push(`Completed ${id}`);save();paths();};window.askTopic=t=>{state.pendingPrompt=`Explain ${t} for ${S().title}. Give the simple meaning, common mistake, memory trick, and one practice question.`;setRoute('tutor');};
function practice(){const qs=QUESTIONS[state.subject];app.innerHTML=`<section class="card"><span class="badge">Practice</span><h2>${S().title} practice</h2><p class="lead">Wrong answers trigger Explain My Mistake.</p><div class="grid">${qs.map((q,i)=>`<button class="module-card" onclick="showQuestion(${i})"><div class="icon ${S().color==='purple'?'purple':''}">?</div><div><h3>${q.topic}</h3><p class="muted">${q.q}</p></div></button>`).join('')}</div></section><section class="card"><span class="badge gold">Infinite practice</span><h2>Generate new practice</h2><div id="infiniteBox">${infinitePracticeHtml()}</div><button class="primary" onclick="newInfinitePractice()">Generate new practice</button></section>`;}window.showQuestion=i=>{const q=QUESTIONS[state.subject][i];app.innerHTML=`<section class="card"><span class="badge">${q.topic}</span><h2>${q.q}</h2>${q.choices.map((c,j)=>`<button class="choice" onclick="answerPractice(${i},${j})">${String.fromCharCode(65+j)}. ${c}</button>`).join('')}<div id="explainBox"></div></section><section class="card"><button class="secondary" onclick="setRoute('practice')">Back</button></section>`;};window.answerPractice=(i,j)=>{const q=QUESTIONS[state.subject][i];state.scores[state.subject].total++;if(j===q.a)state.scores[state.subject].correct++;state.practiceCount[state.subject]=(state.practiceCount[state.subject]||0)+1;document.querySelectorAll('.choice').forEach((b,k)=>{b.disabled=true;if(k===q.a)b.classList.add('correct');if(k===j&&j!==q.a)b.classList.add('wrong')});let box=document.getElementById('explainBox');if(j===q.a){box.innerHTML=`<div class="note"><b>Correct.</b> ${q.trap}<br><b>Next:</b> ${q.retry}</div>`;state.memory[state.subject].known.push(q.topic)}else{state.lastMistake={subject:state.subject,question:q.q,yourAnswer:q.choices[j],correctAnswer:q.choices[q.a],trap:q.trap,retry:q.retry};state.memory[state.subject].weak.push(q.topic);box.innerHTML=`<div class="note warning"><b>Explain my mistake</b><br><b>Your answer:</b> ${q.choices[j]}<br><b>Correct:</b> ${q.choices[q.a]}<br><b>Likely trap:</b> ${q.trap}<br><button class="primary" onclick="askMistake()">Ask Nash deeper</button></div>`;}save();};window.askMistake=()=>{state.pendingPrompt=`Explain my mistake: ${JSON.stringify(state.lastMistake)}. Explain simply, give a memory trick, and one similar practice question.`;setRoute('tutor');};
function rnd(a){return a[Math.floor(Math.random()*a.length)]}function infinitePracticeHtml(){if(state.subject==='eni'){let p=rnd([10,15,18,20,25,30]),c=rnd([2,4,5,6,8]),cac=rnd([40,60,80,90,120]),ten=rnd([4,6,8,10,12]),ltv=(p-c)*ten,ratio=(ltv/cac).toFixed(2),pay=(cac/(p-c)).toFixed(1);return `<div class="note"><b>Unit economics case</b><br>Price $${p}/month · Cost $${c}/month · CAC $${cac} · Tenure ${ten} months<br><b>Task:</b> Calculate LTV, LTV/CAC, payback.<details><summary>Show answer</summary>LTV = $${ltv}. LTV/CAC = ${ratio}×. Payback = ${pay} months.</details></div>`;}let t=rnd([['Translate','I do not understand','No entiendo'],['Translate','Again, please','Otra vez, por favor'],['Complete','Yo ___ llamo Hesham','me'],['Complete','Tú ___ llamas Ana','te'],['Dialogue','Ask someone their name informally','¿Cómo te llamas?']]);return `<div class="note"><b>Spanish A1 practice</b><br><b>${t[0]}:</b> ${t[1]}<details><summary>Show answer</summary>${t[2]}</details></div>`;}window.newInfinitePractice=()=>{state.practiceCount[state.subject]=(state.practiceCount[state.subject]||0)+1;save();document.getElementById('infiniteBox').innerHTML=infinitePracticeHtml();};
function tutor(){const q=state.subject==='eni'?['Quiz me on my weakest topic','Explain CAC vs CPA','Generate a unit economics case','Explain PMF like I am 12']:['Quiz me on Spanish A1','Roleplay a restaurant conversation','Correct: Yo me llamo Hesham','Give me 5 Chile classroom phrases'];app.innerHTML=`<section class="card"><span class="badge">AI Tutor</span><h2>Nash Tutor — ${S().title}</h2><div class="quick"><button onclick="startVoice()">🎤 Speak</button>${q.map(x=>`<button onclick="sendQuick('${x.replaceAll("'","\\'")}')">${x}</button>`).join('')}</div><div id="chat" class="chatbox">${state.chat.slice(-16).map(m=>`<div class="msg ${m.role==='user'?'user':'bot'}"><b>${m.role==='user'?'You':'Nash'}:</b> ${esc(m.content)}</div>`).join('')||'<div class="msg bot"><b>Nash:</b> Ask me anything.</div>'}</div><textarea id="msg" placeholder="Ask Nash...">${state.pendingPrompt||''}</textarea><button class="primary" onclick="sendTutor()">Send to Nash Tutor</button></section>`;state.pendingPrompt='';save();}window.sendQuick=x=>{document.getElementById('msg').value=x;sendTutor();};window.sendTutor=async()=>{const text=document.getElementById('msg').value.trim();if(!text)return;state.chat.push({role:'user',content:text});save();tutor();state.chat.push({role:'assistant',content:'Thinking...'});save();tutor();try{const reply=await askAI(text);state.chat.pop();state.chat.push({role:'assistant',content:reply});save();tutor();}catch(e){state.chat.pop();state.chat.push({role:'assistant',content:'API error. Check Netlify Functions and OPENROUTER_API_KEY.'});save();tutor();}};
window.startVoice=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Voice input is not supported in this browser. Try Chrome.');return;}const r=new SR();r.lang=state.subject==='spanish'?'es-CL':'en-US';r.onresult=e=>{document.getElementById('msg').value=e.results[0][0].transcript;};r.start();};
function flashcards(){const cards=[...FLASHCARDS[state.subject],...(state.generatedFlashcards[state.subject]||[])];let html=cards.map((c,i)=>`<div class="flashcard-wrap"><div class="card flashcard" onclick="this.classList.toggle('flipped')"><div class="front">${esc(c[0])}</div><div class="back">${esc(c[1])}</div></div><button class="secondary" onclick="markKnown('${esc(c[0])}')">I know this</button></div>`).join('');app.innerHTML=`<section class="card"><span class="badge">AI Flashcards</span><h2>${S().title}</h2><p class="lead">Click a card to flip it.</p><div class="grid">${html}</div><hr><h3>Generate new cards with AI</h3><input id="fcTopic" placeholder="Topic, e.g. PMF or restaurant phrases"><button class="primary" onclick="generateFlashcards()">Generate flashcards</button><div id="fcOut"></div></section>`;}window.markKnown=t=>{state.memory[state.subject].known.push(t);save();alert('Saved to learning memory.');};window.generateFlashcards=async()=>{const topic=document.getElementById('fcTopic').value||S().title;const out=document.getElementById('fcOut');out.innerHTML='<div class="note">Generating...</div>';const reply=await askAI(`Create 6 concise flashcards for ${topic}. Format each line as Front | Back. Subject: ${S().title}.`);const parsed=reply.split('\n').map(l=>l.replace(/^[-*\d.\s]+/,'').split('|').map(x=>x.trim())).filter(x=>x.length>=2);state.generatedFlashcards[state.subject].push(...parsed.slice(0,8));save();out.innerHTML=`<div class="note"><b>Added:</b><br>${esc(reply)}</div><button class="primary" onclick="flashcards()">Refresh cards</button>`;};
function mockexam(){app.innerHTML=`<section class="card"><span class="badge">AI Mock Exams</span><h2>${S().title} mock exam</h2><p class="lead">Generate a realistic practice exam for your selected subject.</p><select id="examType"><option>Mixed</option><option>Midterm 1</option><option>Midterm 2</option><option>Final</option><option>Vocabulary</option><option>Grammar</option><option>Reading</option></select><button class="primary" onclick="generateMock()">Generate mock exam</button><div id="mockOut">${(state.mock[state.subject]||[]).map(x=>`<div class="note">${esc(x).replaceAll('\n','<br>')}</div>`).join('')}</div></section>`;}window.generateMock=async()=>{const type=document.getElementById('examType').value;mockOut.innerHTML='<div class="note">Generating exam...</div>';const reply=await askAI(`Generate a ${type} mock exam for ${S().title}. Include 8 questions, answer key at the end, and common traps. Keep it compact.`);state.mock[state.subject].unshift(reply);save();mockexam();};
function conversation(){const scenarios=state.subject==='spanish'?['Restaurant','University classroom','Shopping','Meeting friends','Transport in Santiago']:['Customer interview','Pitch practice','Investor questions','User testing','Pivot decision'];app.innerHTML=`<section class="card"><span class="badge">Conversation Mode</span><h2>${state.subject==='spanish'?'Spanish A1 roleplay':'ENI oral practice'}</h2><p class="lead">Choose a scenario. Nash roleplays, then corrects you.</p><div class="quick">${scenarios.map(s=>`<button onclick="startScenario('${s}')">${s}</button>`).join('')}<button onclick="startVoice()">🎤 Speak answer</button></div><div class="chatbox">${state.conversation.slice(-10).map(m=>`<div class="msg ${m.role==='user'?'user':'bot'}"><b>${m.role==='user'?'You':'Nash'}:</b> ${esc(m.content)}</div>`).join('')||'<div class="msg bot"><b>Nash:</b> Pick a scenario to begin.</div>'}</div><textarea id="convMsg" placeholder="Write your reply..."></textarea><button class="primary" onclick="sendConversation()">Send reply</button></section>`;}window.startScenario=async s=>{state.conversation=[];const prompt=state.subject==='spanish'?`Start a Spanish A1 roleplay scenario: ${s}. You speak first in simple Spanish with English support. Wait for my reply.`:`Start an entrepreneurship oral practice scenario: ${s}. Ask me one realistic course question and wait.`;const reply=await askAI(prompt);state.conversation.push({role:'assistant',content:reply});save();conversation();};window.sendConversation=async()=>{const text=convMsg.value.trim();if(!text)return;state.conversation.push({role:'user',content:text});save();conversation();const reply=await askAI(`Continue this roleplay. Student replied: ${text}. Correct mistakes gently, then ask the next short question.`);state.conversation.push({role:'assistant',content:reply});save();conversation();};
function coach(){app.innerHTML=`<section class="card"><span class="badge">AI Study Coach</span><h2>Today's plan for ${S().title}</h2><p class="lead">Uses your readiness, weak topics, memory, practice count, and uploaded notes.</p><button class="primary" onclick="generateCoach()">Generate today's plan</button><div id="coachOut">${state.coachPlan?`<div class="note">${esc(state.coachPlan).replaceAll('\n','<br>')}</div>`:''}</div></section>`;}window.generateCoach=async()=>{coachOut.innerHTML='<div class="note">Planning...</div>';const reply=await askAI(`Create a personalized 20-minute study plan for ${S().title}. Use my weak topics, readiness score, practice count, and uploaded notes. Include exact steps and estimated minutes.`);state.coachPlan=reply;save();coach();};
function translator(){app.innerHTML=`<section class="card"><span class="badge">Professor Translator</span><h2>Translate confusing course wording</h2><p class="lead">Paste a phrase from class. Nash gives simple meaning, example, common mistake, and memory trick.</p><textarea id="phrase" placeholder="e.g. validated learning / ¿Cómo se dice...? / riskiest assumption"></textarea><button class="primary" onclick="translatePhrase()">Translate it</button><div id="transOut"></div></section>`;}window.translatePhrase=async()=>{const p=phrase.value.trim();if(!p)return;transOut.innerHTML='<div class="note">Translating...</div>';const reply=await askAI(`Professor translator mode for ${S().title}. Explain this phrase: "${p}". Output: simple meaning, example, common mistake, memory trick, one practice question.`);transOut.innerHTML=`<div class="note">${esc(reply).replaceAll('\n','<br>')}</div>`;};
function upload(){app.innerHTML=`<section class="card"><span class="badge">Upload / Paste Notes</span><h2>Add material for Nash</h2><p class="lead">Upload a text file or paste notes from slides. For PDFs, copy/paste the important text here. Nash will use the latest notes as context.</p><input type="file" id="fileInput" accept=".txt,.md,.csv,.pdf"><button class="secondary" onclick="readFile()">Save uploaded file name/text</button><label>Paste slide notes or summary</label><textarea id="pasteNotes" placeholder="Paste lecture text, vocabulary, or exam list..."></textarea><button class="primary" onclick="savePastedNotes()">Save notes to Nash memory</button><div>${state.uploads.map((u,i)=>`<div class="note"><b>${esc(u.name)}</b><br>${esc((u.text||'').slice(0,220))}...</div>`).join('')}</div></section>`;}window.readFile=()=>{const f=fileInput.files[0];if(!f)return alert('Choose a file first.');const reader=new FileReader();reader.onload=()=>{state.uploads.push({name:f.name,text:String(reader.result||'').slice(0,4000),time:new Date().toISOString(),subject:state.subject});save();upload();};reader.readAsText(f);};window.savePastedNotes=()=>{if(!pasteNotes.value.trim())return;state.uploads.push({name:`Pasted notes — ${S().title}`,text:pasteNotes.value,time:new Date().toISOString(),subject:state.subject});save();upload();};
function memory(){const m=state.memory[state.subject];app.innerHTML=`<section class="card"><span class="badge">Learning Memory</span><h2>${S().title}</h2><div class="grid"><div class="note"><b>Known topics</b><br>${[...new Set(m.known)].slice(-20).join('<br>')||'Nothing yet.'}</div><div class="note warning"><b>Weak topics</b><br>${[...new Set(m.weak)].slice(-20).join('<br>')||'Nothing yet.'}</div></div><h3>Manual memory update</h3><input id="weakTopic" placeholder="Add weak topic"><button class="secondary" onclick="addWeak()">Add weak topic</button><button class="primary" onclick="generateCoach()">Generate plan from memory</button></section>`;}window.addWeak=()=>{if(weakTopic.value.trim())state.memory[state.subject].weak.push(weakTopic.value.trim());save();memory();};
function feedback(){app.innerHTML=`<section class="card"><span class="badge">Feedback</span><h2>Help improve Nash</h2><label>What worked?</label><textarea id="fb1"></textarea><label>What should improve?</label><textarea id="fb2"></textarea><button class="primary" onclick="saveFeedback()">Save feedback locally</button></section>`;}window.saveFeedback=()=>{state.feedback.push({time:new Date().toISOString(),subject:state.subject,worked:fb1.value,improve:fb2.value});save();alert('Saved.');};
function render(){navActive();({home,dashboard,paths,practice,tutor,flashcards,mockexam,conversation,coach,translator,upload,memory,feedback}[state.route]||home)();navActive();}render();
